### ISSUE TITLE
how was creating integrated FAQ menu?

### ISSUE THREAD

**Issue by dakeshi** [Loopring/loopring.org#4]
we has two FAQ page

- dev portal(https://loopring.org/faq.html)
- resource(https://loopring.org/resources.html)

it's the same content excepting FAQ of dev portal has more. So, it looks duplicated.

Why don't you integrated FAQ as separate menu(in the top)?
I think that it's good idea to maintain with specific section(the way of current dev portal's FAQ)

**Comment by dong77** [comment]
good idea. WIll give it a try.

**Comment by dong77** [comment]
Resolved
